# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

apt_packages:
 - gdal-bin
 - libgdal-dev
 
install:
  - ./travis-tool.sh github_package jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
